using System.Drawing;
namespace Redsoft
{
    partial class d_jl_h_updt
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            this.panel1 = new System.Windows.Forms.Panel();
            
 this.bianhao_t=new System.Windows.Forms.Label();
 this.bianhao=new Redsoft.MyTextBox();
 this.baofei_t=new System.Windows.Forms.Label();
 this.baofei=new Redsoft.MyTextBox();
 this.ljmc_t=new System.Windows.Forms.Label();
 this.ljmc=new Redsoft.MyTextBox();
 this.xinghao_t=new System.Windows.Forms.Label();
 this.xinghao=new Redsoft.MyTextBox();
 this.clfw_t=new System.Windows.Forms.Label();
 this.clfw=new Redsoft.MyTextBox();
 this.fbl_t=new System.Windows.Forms.Label();
 this.fbl=new Redsoft.MyTextBox();
 this.sydd_t=new System.Windows.Forms.Label();
 this.syr_t=new System.Windows.Forms.Label();
 this.riqi_songjian_t=new System.Windows.Forms.Label();
 this.zhuangtai_t=new System.Windows.Forms.Label();
 this.bz_t=new System.Windows.Forms.Label();
 this.bz=new Redsoft.MyTextBox();
 this.sydd=new Redsoft.MyTextBox();
 this.syr=new Redsoft.MyTextBox();
 this.riqi_songjian=new Redsoft.MyTextBox();
 this.zhuangtai=new Redsoft.MyTextBox();
 this.lrsj_t=new System.Windows.Forms.Label();
 this.riqi_scys_t=new System.Windows.Forms.Label();
 this.zhouqi_w_t=new System.Windows.Forms.Label();
 this.zhouqi_n_t=new System.Windows.Forms.Label();
 this.riqi_scys=new Redsoft.MyTextBox();
 this.zhouqi_w=new Redsoft.MyTextBox();
 this.zhouqi_n=new Redsoft.MyTextBox();
 this.riqi_jhn_t=new System.Windows.Forms.Label();
 this.riqi_jhw_t=new System.Windows.Forms.Label();
 this.jl_id_t=new System.Windows.Forms.Label();
 this.riqi_jhn=new Redsoft.MyTextBox();
 this.riqi_jhw=new Redsoft.MyTextBox();
 this.jl_id=new Redsoft.MyTextBox();
 this.riqi_w_t=new System.Windows.Forms.Label();
 this.riqi_n_t=new System.Windows.Forms.Label();
 this.riqi_scjd_t=new System.Windows.Forms.Label();
 this.riqi_n=new Redsoft.MyTextBox();
 this.riqi_w=new Redsoft.MyTextBox();
 this.riqi_scjd=new Redsoft.MyTextBox();
 this.riqiwn=new Redsoft.MyTextBox();
 this.lrr=new Redsoft.MyTextBox();
 this.lrsj=new Redsoft.MyTextBox();
 this.xgsj_t=new System.Windows.Forms.Label();
 this.xgsj=new Redsoft.MyTextBox();
 this.lrr_t=new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            
  this.panel1.Controls.Add(bianhao_t);
  this.panel1.Controls.Add(bianhao);
  this.panel1.Controls.Add(baofei_t);
  this.panel1.Controls.Add(baofei);
  this.panel1.Controls.Add(ljmc_t);
  this.panel1.Controls.Add(ljmc);
  this.panel1.Controls.Add(xinghao_t);
  this.panel1.Controls.Add(xinghao);
  this.panel1.Controls.Add(clfw_t);
  this.panel1.Controls.Add(clfw);
  this.panel1.Controls.Add(fbl_t);
  this.panel1.Controls.Add(fbl);
  this.panel1.Controls.Add(sydd_t);
  this.panel1.Controls.Add(syr_t);
  this.panel1.Controls.Add(riqi_songjian_t);
  this.panel1.Controls.Add(zhuangtai_t);
  this.panel1.Controls.Add(bz_t);
  this.panel1.Controls.Add(bz);
  this.panel1.Controls.Add(sydd);
  this.panel1.Controls.Add(syr);
  this.panel1.Controls.Add(riqi_songjian);
  this.panel1.Controls.Add(zhuangtai);
  this.panel1.Controls.Add(lrsj_t);
  this.panel1.Controls.Add(riqi_scys_t);
  this.panel1.Controls.Add(zhouqi_w_t);
  this.panel1.Controls.Add(zhouqi_n_t);
  this.panel1.Controls.Add(riqi_scys);
  this.panel1.Controls.Add(zhouqi_w);
  this.panel1.Controls.Add(zhouqi_n);
  this.panel1.Controls.Add(riqi_jhn_t);
  this.panel1.Controls.Add(riqi_jhw_t);
  this.panel1.Controls.Add(jl_id_t);
  this.panel1.Controls.Add(riqi_jhn);
  this.panel1.Controls.Add(riqi_jhw);
  this.panel1.Controls.Add(jl_id);
  this.panel1.Controls.Add(riqi_w_t);
  this.panel1.Controls.Add(riqi_n_t);
  this.panel1.Controls.Add(riqi_scjd_t);
  this.panel1.Controls.Add(riqi_n);
  this.panel1.Controls.Add(riqi_w);
  this.panel1.Controls.Add(riqi_scjd);
  this.panel1.Controls.Add(riqiwn);
  this.panel1.Controls.Add(lrr);
  this.panel1.Controls.Add(lrsj);
  this.panel1.Controls.Add(xgsj_t);
  this.panel1.Controls.Add(xgsj);
  this.panel1.Controls.Add(lrr_t);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(741, 418);
            this.panel1.TabIndex = 0;
            
  jl_id.AllowUpdate = "1";
  baofei.AllowUpdate = "1";
  ljmc.AllowUpdate = "1";
  bianhao.AllowUpdate = "1";
  xinghao.AllowUpdate = "1";
  clfw.AllowUpdate = "1";
  fbl.AllowUpdate = "1";
  sydd.AllowUpdate = "1";
  syr.AllowUpdate = "1";
  riqi_scys.AllowUpdate = "1";
  riqi_scjd.AllowUpdate = "1";
  zhouqi_w.AllowUpdate = "1";
  zhouqi_n.AllowUpdate = "1";
  riqi_w.AllowUpdate = "1";
  riqi_n.AllowUpdate = "1";
  riqi_songjian.AllowUpdate = "1";
  bz.AllowUpdate = "1";
  zhuangtai.AllowUpdate = "1";
  lrr.AllowUpdate = "1";
  lrsj.AllowUpdate = "0";
  xgsj.AllowUpdate = "1";
  riqi_jhw.AllowUpdate = "1";
  riqi_jhn.AllowUpdate = "1";
  riqiwn.AllowUpdate = "1";
 bianhao_t.Location = new System.Drawing.Point(9, 7);
  bianhao_t.Name = "bianhao_t";
  bianhao_t.TextAlign = ContentAlignment.MiddleRight;
  bianhao_t.Size = new System.Drawing.Size(99, 23);
  bianhao_t.Text = "编号";
  bianhao_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  bianhao_t.Visible = true;
  bianhao_t.Text = "编号";
  bianhao.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 bianhao.Location = new System.Drawing.Point(117, 7);
  bianhao.Name = "bianhao";
  bianhao.Size = new System.Drawing.Size(374, 26);
 bianhao.TabIndex = 10;
  bianhao.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  bianhao.BackColor =  ColorTranslator.FromWin32(16777215);
  bianhao.MaxLength = 100;
  bianhao.Visible = true;
 baofei_t.Location = new System.Drawing.Point(506, 7);
  baofei_t.Name = "baofei_t";
  baofei_t.TextAlign = ContentAlignment.MiddleRight;
  baofei_t.Size = new System.Drawing.Size(99, 23);
  baofei_t.Text = "报废";
  baofei_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  baofei_t.Visible = true;
  baofei_t.Text = "报废";
  baofei.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 baofei.Location = new System.Drawing.Point(612, 7);
  baofei.Name = "baofei";
  baofei.Size = new System.Drawing.Size(374, 26);
 baofei.TabIndex = 190;
  baofei.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  baofei.BackColor =  ColorTranslator.FromWin32(553648127);
  baofei.MaxLength = 1;
  baofei.Visible = true;
 ljmc_t.Location = new System.Drawing.Point(9, 43);
  ljmc_t.Name = "ljmc_t";
  ljmc_t.TextAlign = ContentAlignment.MiddleRight;
  ljmc_t.Size = new System.Drawing.Size(99, 23);
  ljmc_t.Text = "量具名称";
  ljmc_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  ljmc_t.Visible = true;
  ljmc_t.Text = "量具名称";
  ljmc.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 ljmc.Location = new System.Drawing.Point(117, 43);
  ljmc.Name = "ljmc";
  ljmc.Size = new System.Drawing.Size(374, 26);
 ljmc.TabIndex = 20;
  ljmc.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  ljmc.BackColor =  ColorTranslator.FromWin32(16777215);
  ljmc.MaxLength = 100;
  ljmc.Visible = true;
 xinghao_t.Location = new System.Drawing.Point(506, 43);
  xinghao_t.Name = "xinghao_t";
  xinghao_t.TextAlign = ContentAlignment.MiddleRight;
  xinghao_t.Size = new System.Drawing.Size(99, 23);
  xinghao_t.Text = "型号";
  xinghao_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  xinghao_t.Visible = true;
  xinghao_t.Text = "型号";
  xinghao.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 xinghao.Location = new System.Drawing.Point(612, 43);
  xinghao.Name = "xinghao";
  xinghao.Size = new System.Drawing.Size(374, 26);
 xinghao.TabIndex = 30;
  xinghao.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  xinghao.BackColor =  ColorTranslator.FromWin32(16777215);
  xinghao.MaxLength = 100;
  xinghao.Visible = true;
 clfw_t.Location = new System.Drawing.Point(9, 80);
  clfw_t.Name = "clfw_t";
  clfw_t.TextAlign = ContentAlignment.MiddleRight;
  clfw_t.Size = new System.Drawing.Size(100, 23);
  clfw_t.Text = "测量范围";
  clfw_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  clfw_t.Visible = true;
  clfw_t.Text = "测量范围";
  clfw.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 clfw.Location = new System.Drawing.Point(117, 80);
  clfw.Name = "clfw";
  clfw.Size = new System.Drawing.Size(374, 26);
 clfw.TabIndex = 40;
  clfw.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  clfw.BackColor =  ColorTranslator.FromWin32(16777215);
  clfw.MaxLength = 100;
  clfw.Visible = true;
 fbl_t.Location = new System.Drawing.Point(506, 80);
  fbl_t.Name = "fbl_t";
  fbl_t.TextAlign = ContentAlignment.MiddleRight;
  fbl_t.Size = new System.Drawing.Size(100, 23);
  fbl_t.Text = "分辨率";
  fbl_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  fbl_t.Visible = true;
  fbl_t.Text = "分辨率";
  fbl.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 fbl.Location = new System.Drawing.Point(612, 80);
  fbl.Name = "fbl";
  fbl.Size = new System.Drawing.Size(374, 26);
 fbl.TabIndex = 50;
  fbl.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  fbl.BackColor =  ColorTranslator.FromWin32(16777215);
  fbl.MaxLength = 100;
  fbl.Visible = true;
 sydd_t.Location = new System.Drawing.Point(9, 117);
  sydd_t.Name = "sydd_t";
  sydd_t.TextAlign = ContentAlignment.MiddleRight;
  sydd_t.Size = new System.Drawing.Size(100, 23);
  sydd_t.Text = "使用地点";
  sydd_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  sydd_t.Visible = true;
  sydd_t.Text = "使用地点";
 syr_t.Location = new System.Drawing.Point(506, 117);
  syr_t.Name = "syr_t";
  syr_t.TextAlign = ContentAlignment.MiddleRight;
  syr_t.Size = new System.Drawing.Size(99, 23);
  syr_t.Text = "使用人";
  syr_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  syr_t.Visible = true;
  syr_t.Text = "使用人";
 riqi_songjian_t.Location = new System.Drawing.Point(9, 267);
  riqi_songjian_t.Name = "riqi_songjian_t";
  riqi_songjian_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_songjian_t.Size = new System.Drawing.Size(100, 23);
  riqi_songjian_t.Text = "送检日期";
  riqi_songjian_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_songjian_t.Visible = true;
  riqi_songjian_t.Text = "送检日期";
 zhuangtai_t.Location = new System.Drawing.Point(506, 267);
  zhuangtai_t.Name = "zhuangtai_t";
  zhuangtai_t.TextAlign = ContentAlignment.MiddleRight;
  zhuangtai_t.Size = new System.Drawing.Size(100, 23);
  zhuangtai_t.Text = "状态";
  zhuangtai_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  zhuangtai_t.Visible = true;
  zhuangtai_t.Text = "状态";
 bz_t.Location = new System.Drawing.Point(9, 305);
  bz_t.Name = "bz_t";
  bz_t.TextAlign = ContentAlignment.MiddleRight;
  bz_t.Size = new System.Drawing.Size(99, 23);
  bz_t.Text = "备注";
  bz_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  bz_t.Visible = true;
  bz_t.Text = "备注";
  bz.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 bz.Location = new System.Drawing.Point(117, 305);
  bz.Name = "bz";
  bz.Size = new System.Drawing.Size(870, 26);
 bz.TabIndex = 100;
  bz.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  bz.BackColor =  ColorTranslator.FromWin32(16777215);
  bz.MaxLength = 100;
  bz.Visible = true;
  sydd.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 sydd.Location = new System.Drawing.Point(117, 117);
  sydd.Name = "sydd";
  sydd.Size = new System.Drawing.Size(374, 26);
 sydd.TabIndex = 110;
  sydd.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  sydd.BackColor =  ColorTranslator.FromWin32(553648127);
  sydd.MaxLength = 100;
  sydd.Visible = true;
  syr.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 syr.Location = new System.Drawing.Point(612, 117);
  syr.Name = "syr";
  syr.Size = new System.Drawing.Size(374, 26);
 syr.TabIndex = 120;
  syr.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  syr.BackColor =  ColorTranslator.FromWin32(553648127);
  syr.MaxLength = 100;
  syr.Visible = true;
  riqi_songjian.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_songjian.Location = new System.Drawing.Point(117, 267);
  riqi_songjian.Name = "riqi_songjian";
  riqi_songjian.Size = new System.Drawing.Size(374, 26);
 riqi_songjian.TabIndex = 150;
  riqi_songjian.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_songjian.BackColor =  ColorTranslator.FromWin32(553648127);
  riqi_songjian.Visible = true;
  riqi_songjian.Tag = "yyyy-mm-dd";
  zhuangtai.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 zhuangtai.Location = new System.Drawing.Point(612, 267);
  zhuangtai.Name = "zhuangtai";
  zhuangtai.Size = new System.Drawing.Size(374, 26);
 zhuangtai.TabIndex = 160;
  zhuangtai.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  zhuangtai.BackColor =  ColorTranslator.FromWin32(553648127);
  zhuangtai.MaxLength = 100;
  zhuangtai.Visible = true;
 lrsj_t.Location = new System.Drawing.Point(10, 344);
  lrsj_t.Name = "lrsj_t";
  lrsj_t.TextAlign = ContentAlignment.MiddleRight;
  lrsj_t.Size = new System.Drawing.Size(99, 23);
  lrsj_t.Text = "录入时间";
  lrsj_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  lrsj_t.Visible = true;
  lrsj_t.Text = "录入时间";
 riqi_scys_t.Location = new System.Drawing.Point(9, 153);
  riqi_scys_t.Name = "riqi_scys_t";
  riqi_scys_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_scys_t.Size = new System.Drawing.Size(149, 23);
  riqi_scys_t.Text = "首次验收日期";
  riqi_scys_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_scys_t.Visible = true;
  riqi_scys_t.Text = "首次验收日期";
  riqi_scys_t.Tag = "_1h";
 zhouqi_w_t.Location = new System.Drawing.Point(9, 192);
  zhouqi_w_t.Name = "zhouqi_w_t";
  zhouqi_w_t.TextAlign = ContentAlignment.MiddleRight;
  zhouqi_w_t.Size = new System.Drawing.Size(149, 23);
  zhouqi_w_t.Text = "外检周期";
  zhouqi_w_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  zhouqi_w_t.Visible = true;
  zhouqi_w_t.Text = "外检周期";
 zhouqi_n_t.Location = new System.Drawing.Point(9, 231);
  zhouqi_n_t.Name = "zhouqi_n_t";
  zhouqi_n_t.TextAlign = ContentAlignment.MiddleRight;
  zhouqi_n_t.Size = new System.Drawing.Size(149, 23);
  zhouqi_n_t.Text = "内检周期";
  zhouqi_n_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  zhouqi_n_t.Visible = true;
  zhouqi_n_t.Text = "内检周期";
  riqi_scys.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_scys.Location = new System.Drawing.Point(166, 153);
  riqi_scys.Name = "riqi_scys";
  riqi_scys.Size = new System.Drawing.Size(149, 26);
 riqi_scys.TabIndex = 60;
  riqi_scys.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_scys.BackColor =  ColorTranslator.FromWin32(16777215);
  riqi_scys.Visible = true;
  riqi_scys.Tag = "yyyy-mm-dd";
  zhouqi_w.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 zhouqi_w.Location = new System.Drawing.Point(166, 192);
  zhouqi_w.Name = "zhouqi_w";
  zhouqi_w.Size = new System.Drawing.Size(149, 26);
 zhouqi_w.TabIndex = 80;
  zhouqi_w.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  zhouqi_w.BackColor =  ColorTranslator.FromWin32(16777215);
  zhouqi_w.Visible = true;
  zhouqi_n.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 zhouqi_n.Location = new System.Drawing.Point(166, 231);
  zhouqi_n.Name = "zhouqi_n";
  zhouqi_n.Size = new System.Drawing.Size(149, 26);
 zhouqi_n.TabIndex = 90;
  zhouqi_n.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  zhouqi_n.BackColor =  ColorTranslator.FromWin32(16777215);
  zhouqi_n.Visible = true;
 riqi_jhn_t.Location = new System.Drawing.Point(681, 231);
  riqi_jhn_t.Name = "riqi_jhn_t";
  riqi_jhn_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_jhn_t.Size = new System.Drawing.Size(149, 23);
  riqi_jhn_t.Text = "内检下次检定日期";
  riqi_jhn_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_jhn_t.Visible = true;
  riqi_jhn_t.Text = "内检下次检定日期";
 riqi_jhw_t.Location = new System.Drawing.Point(681, 192);
  riqi_jhw_t.Name = "riqi_jhw_t";
  riqi_jhw_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_jhw_t.Size = new System.Drawing.Size(149, 23);
  riqi_jhw_t.Text = "外检下次检定日期";
  riqi_jhw_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_jhw_t.Visible = true;
  riqi_jhw_t.Text = "外检下次检定日期";
 jl_id_t.Location = new System.Drawing.Point(681, 155);
  jl_id_t.Name = "jl_id_t";
  jl_id_t.TextAlign = ContentAlignment.MiddleRight;
  jl_id_t.Size = new System.Drawing.Size(149, 23);
  jl_id_t.Text = "计量ID";
  jl_id_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  jl_id_t.Visible = true;
  jl_id_t.Text = "计量ID";
  riqi_jhn.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_jhn.Location = new System.Drawing.Point(837, 231);
  riqi_jhn.Name = "riqi_jhn";
  riqi_jhn.Size = new System.Drawing.Size(149, 23);
 riqi_jhn.TabIndex = 210;
  riqi_jhn.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_jhn.BackColor =  ColorTranslator.FromWin32(553648127);
  riqi_jhn.ReadOnly = true;
  riqi_jhn.BackColor =  SystemColors.Control;
  riqi_jhn.Visible = true;
  riqi_jhw.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_jhw.Location = new System.Drawing.Point(837, 192);
  riqi_jhw.Name = "riqi_jhw";
  riqi_jhw.Size = new System.Drawing.Size(149, 23);
 riqi_jhw.TabIndex = 200;
  riqi_jhw.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_jhw.BackColor =  ColorTranslator.FromWin32(553648127);
  riqi_jhw.ReadOnly = true;
  riqi_jhw.BackColor =  SystemColors.Control;
  riqi_jhw.Visible = true;
  jl_id.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 jl_id.Location = new System.Drawing.Point(837, 155);
  jl_id.Name = "jl_id";
  jl_id.Size = new System.Drawing.Size(149, 26);
 jl_id.TabIndex = 32766;
  jl_id.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  jl_id.BackColor =  ColorTranslator.FromWin32(553648127);
  jl_id.Visible = true;
 riqi_w_t.Location = new System.Drawing.Point(345, 192);
  riqi_w_t.Name = "riqi_w_t";
  riqi_w_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_w_t.Size = new System.Drawing.Size(149, 23);
  riqi_w_t.Text = "外检最后检定日期";
  riqi_w_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_w_t.Visible = true;
  riqi_w_t.Text = "外检最后检定日期";
 riqi_n_t.Location = new System.Drawing.Point(345, 231);
  riqi_n_t.Name = "riqi_n_t";
  riqi_n_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_n_t.Size = new System.Drawing.Size(149, 23);
  riqi_n_t.Text = "内检最后检定日期";
  riqi_n_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_n_t.Visible = true;
  riqi_n_t.Text = "内检最后检定日期";
 riqi_scjd_t.Location = new System.Drawing.Point(345, 153);
  riqi_scjd_t.Name = "riqi_scjd_t";
  riqi_scjd_t.TextAlign = ContentAlignment.MiddleRight;
  riqi_scjd_t.Size = new System.Drawing.Size(149, 23);
  riqi_scjd_t.Text = "首次检定日期";
  riqi_scjd_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_scjd_t.Visible = true;
  riqi_scjd_t.Text = "首次检定日期";
  riqi_scjd_t.Tag = "_1h";
  riqi_n.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_n.Location = new System.Drawing.Point(501, 231);
  riqi_n.Name = "riqi_n";
  riqi_n.Size = new System.Drawing.Size(149, 26);
 riqi_n.TabIndex = 140;
  riqi_n.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_n.BackColor =  ColorTranslator.FromWin32(553648127);
  riqi_n.ReadOnly = true;
  riqi_n.BackColor =  SystemColors.Control;
  riqi_n.Visible = true;
  riqi_n.Tag = "yyyy-mm-dd";
  riqi_w.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_w.Location = new System.Drawing.Point(501, 192);
  riqi_w.Name = "riqi_w";
  riqi_w.Size = new System.Drawing.Size(149, 26);
 riqi_w.TabIndex = 130;
  riqi_w.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_w.BackColor =  ColorTranslator.FromWin32(553648127);
  riqi_w.ReadOnly = true;
  riqi_w.BackColor =  SystemColors.Control;
  riqi_w.Visible = true;
  riqi_w.Tag = "yyyy-mm-dd";
  riqi_scjd.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 riqi_scjd.Location = new System.Drawing.Point(501, 153);
  riqi_scjd.Name = "riqi_scjd";
  riqi_scjd.Size = new System.Drawing.Size(149, 26);
 riqi_scjd.TabIndex = 70;
  riqi_scjd.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqi_scjd.BackColor =  ColorTranslator.FromWin32(16777215);
  riqi_scjd.Visible = true;
  riqi_scjd.Tag = "yyyy-mm-dd";
 riqiwn.Location = new System.Drawing.Point(1014, 118);
  riqiwn.Name = "riqiwn";
  riqiwn.Size = new System.Drawing.Size(152, 23);
 riqiwn.TabIndex = 220;
  riqiwn.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  riqiwn.BackColor =  ColorTranslator.FromWin32(16777215);
  riqiwn.Visible = false;
 lrr.Location = new System.Drawing.Point(747, 344);
  lrr.Name = "lrr";
  lrr.Size = new System.Drawing.Size(138, 23);
 lrr.TabIndex = 230;
  lrr.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  lrr.BackColor =  ColorTranslator.FromWin32(553648127);
  lrr.ReadOnly = true;
  lrr.BackColor =  SystemColors.Control;
  lrr.Visible = true;
  lrsj.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 lrsj.Location = new System.Drawing.Point(118, 343);
  lrsj.Name = "lrsj";
  lrsj.Size = new System.Drawing.Size(200, 23);
 lrsj.TabIndex = 170;
  lrsj.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  lrsj.BackColor =  ColorTranslator.FromWin32(553648127);
  lrsj.ReadOnly = true;
  lrsj.BackColor =  SystemColors.Control;
  lrsj.Visible = true;
 xgsj_t.Location = new System.Drawing.Point(325, 345);
  xgsj_t.Name = "xgsj_t";
  xgsj_t.TextAlign = ContentAlignment.MiddleRight;
  xgsj_t.Size = new System.Drawing.Size(99, 23);
  xgsj_t.Text = "修改时间";
  xgsj_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  xgsj_t.Visible = true;
  xgsj_t.Text = "修改时间";
  xgsj.BorderStyle =System.Windows.Forms.BorderStyle.Fixed3D;
 xgsj.Location = new System.Drawing.Point(433, 343);
  xgsj.Name = "xgsj";
  xgsj.Size = new System.Drawing.Size(200, 23);
 xgsj.TabIndex = 180;
  xgsj.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  xgsj.BackColor =  ColorTranslator.FromWin32(553648127);
  xgsj.ReadOnly = true;
  xgsj.BackColor =  SystemColors.Control;
  xgsj.Visible = true;
 lrr_t.Location = new System.Drawing.Point(641, 344);
  lrr_t.Name = "lrr_t";
  lrr_t.TextAlign = ContentAlignment.MiddleRight;
  lrr_t.Size = new System.Drawing.Size(99, 23);
  lrr_t.Text = "修改人";
  lrr_t.Font = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
  lrr_t.Visible = true;
  lrr_t.Text = "修改人";
            // 
            // UserControl2
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.panel1);
            this.Name = "d_jl_h_updt";
            this.Size = new System.Drawing.Size(741, 418);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.Panel panel1;
        
 System.Windows.Forms.Label bianhao_t;
 Redsoft.MyTextBox bianhao;
 System.Windows.Forms.Label baofei_t;
 Redsoft.MyTextBox baofei;
 System.Windows.Forms.Label ljmc_t;
 Redsoft.MyTextBox ljmc;
 System.Windows.Forms.Label xinghao_t;
 Redsoft.MyTextBox xinghao;
 System.Windows.Forms.Label clfw_t;
 Redsoft.MyTextBox clfw;
 System.Windows.Forms.Label fbl_t;
 Redsoft.MyTextBox fbl;
 System.Windows.Forms.Label sydd_t;
 System.Windows.Forms.Label syr_t;
 System.Windows.Forms.Label riqi_songjian_t;
 System.Windows.Forms.Label zhuangtai_t;
 System.Windows.Forms.Label bz_t;
 Redsoft.MyTextBox bz;
 Redsoft.MyTextBox sydd;
 Redsoft.MyTextBox syr;
 Redsoft.MyTextBox riqi_songjian;
 Redsoft.MyTextBox zhuangtai;
 System.Windows.Forms.Label lrsj_t;
 System.Windows.Forms.Label riqi_scys_t;
 System.Windows.Forms.Label zhouqi_w_t;
 System.Windows.Forms.Label zhouqi_n_t;
 Redsoft.MyTextBox riqi_scys;
 Redsoft.MyTextBox zhouqi_w;
 Redsoft.MyTextBox zhouqi_n;
 System.Windows.Forms.Label riqi_jhn_t;
 System.Windows.Forms.Label riqi_jhw_t;
 System.Windows.Forms.Label jl_id_t;
 Redsoft.MyTextBox riqi_jhn;
 Redsoft.MyTextBox riqi_jhw;
 Redsoft.MyTextBox jl_id;
 System.Windows.Forms.Label riqi_w_t;
 System.Windows.Forms.Label riqi_n_t;
 System.Windows.Forms.Label riqi_scjd_t;
 Redsoft.MyTextBox riqi_n;
 Redsoft.MyTextBox riqi_w;
 Redsoft.MyTextBox riqi_scjd;
 Redsoft.MyTextBox riqiwn;
 Redsoft.MyTextBox lrr;
 Redsoft.MyTextBox lrsj;
 System.Windows.Forms.Label xgsj_t;
 Redsoft.MyTextBox xgsj;
 System.Windows.Forms.Label lrr_t;

    }
}
